apiVersion: v1
kind: Pod
metadata:
  name: ollama-pod
  labels:
    app: ollama
spec:
  containers:
  - name: ollama
    image: ollama/ollama
    ports:
    - containerPort: 11434
      hostPort: 11434
    env:
    - name: OLLAMA_CONTEXT_LENGTH
      value: "32000"
    volumeMounts:
    - name: ollama-data
      mountPath: /root/.ollama
  volumes:
  - name: ollama-data
    hostPath:
      path: /home/dadoms2/ollama # Sostituisci USER con il tuo nome utente o path assoluto
      type: DirectoryOrCreate